# Generated by Django 4.0.4 on 2022-05-19 07:54

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expire_date', models.DateTimeField()),
                ('result', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='VoteChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vote.choice')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vote.vote')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='choices',
            field=models.ManyToManyField(through='app_vote.VoteChoices', to='app_vote.choice'),
        ),
        migrations.AddField(
            model_name='vote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserVoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vote.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vote.vote')),
            ],
        ),
        migrations.AddIndex(
            model_name='choice',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title'], name='app_vote_ch_title_008327_hash'),
        ),
        migrations.AddIndex(
            model_name='uservotehistory',
            index=models.Index(fields=['user', 'vote'], name='app_vote_us_user_id_616c6a_idx'),
        ),
    ]
