version: "3.8"

services:
    postgres:
        image: postgres
        container_name: 'twitter-postgres'
        command: ["postgres", "-c", "log_statement=all"]
        restart: "no"
        ports:
            - "5432:5432"
        expose:
            - 5432
        environment:
            POSTGRES_DB: "twitter"
            POSTGRES_USER: "twitter"
            POSTGRES_PASSWORD: "twitter"

        volumes:
            - postgres-data:/var/lib/postgresql/data/

    redis:
        image: redis
        container_name: 'twitter-redis'
        restart: "no"
        ports:
            - "6379:6379"
        expose:
            - 6379
        volumes:
            - redis-data:/data

volumes:
    postgres-data:
    redis-data:
