# Generated by Django 4.0.4 on 2022-05-19 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('like', 'like'), ('retweet', 'retweet'), ('mention', 'mention'), ('message', 'message'), ('EVENT', 'event')], default='mention', max_length=8)),
                ('group', models.CharField(choices=[('twitter', 'twitter')], default='twitter', max_length=32)),
                ('object_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(default=None, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_actions', to='contenttypes.contenttype')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_performed', to=settings.AUTH_USER_MODEL)),
                ('performed_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='app_notific_created_7ffe4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id', 'type', 'group'], name='app_notific_content_c8564a_idx'),
        ),
    ]
